# Things you need to change
# 1. data -> Place where the graphs are stored (each graph in a separate folder) 
# 2. output -> Output dir
# Rest should stay the same for this project


data: ../data/input/
output: ../results/

chr:
  - chr1
  - chr2
  - chr3
  - chr4
  - chr5

chr1:
  - Chr1
  - Chr2
  - Chr3
  - Chr4
  - Chr5

path:
  - 10002
  - 10015
  - 10024
  - 1741
  - 22002
  - 22003
  - 22004
  - 22005
  - 22006
  - 22007
  - 6024
  - 6069
  - 6124
  - 6244
  - 6909
  - 6966
  - 8236
  - 9075
  - 9537
  - 9543
  - 9638
  - 9728
  - 9764
  - 9888
  - 9905
  - 9981
  - TAIR10
  - 22001
