base: /ebio/abt6_projects9/1001g_plus_pan/data/analysis/1001Gplus_paper/02_analysis/12_graph/SVoverlap/
data: /ebio/abt6_projects9/1001g_plus_pan/data/analysis/1001Gplus_paper/02_analysis/12_graph/SVoverlap/data/


cutoff:
  - 50000
  - 10000
  - 100000
  - 20000
  - 10000000000