---
title: "Graph of TEs"
# output: html_notebook
output: null_document
---

This file contains a basic pipeline for creating a graph of nestedness 
taking into account counts of the "same" sequences (sim.cutoff).

# Setup
```{r, message=FALSE}
# library(ggplot2)
# library(reshape2)
library(viridis)
library(colorRamps)
library(gridExtra)
library(ggplot2)
library(ggnet)
library(network)
library(khroma)
library(dplyr)
library(igraph)

source('similarity.R')
source('graph_refinement.R')

sunset <- colour("sunset")
discrete_rainbow <- colour("discrete rainbow")

sim.cutoff = 0.85

```


# Read Example
```{r}

bl.file = 'example_graph_5comp.txt'
bl.res = read.table(bl.file, stringsAsFactors = F)

i.len.field = 5

```

# Graph construction
## Whole graph
```{r}
g.content.comp = getGraphFromBlast(bl.res, sim.cutoff = sim.cutoff, i.len.field = i.len.field, collapse = T, refine = F)

g.part <- network(g.content.comp$edges, matrix.type = "edgelist", ignore.eval = FALSE, directed = TRUE)
b.graph.names = network.vertex.names(g.part)
set.seed(239)
p.init <- ggnet2(g.part, label = F, edge.color = "black",
            # node.size = g.nodes.cnt[b.graph.names],
            node.size = 1,
            color = '#468B97',
            arrow.gap = 0.01, arrow.size = 2,
            # color = g.nodes.fam[b.graph.names],
            # palette = fam.palette,
            # mode = "kamadakawai"
            )
```


## Refined graph
```{r}
g.content.comp = getGraphFromBlast(bl.res, sim.cutoff = sim.cutoff, i.len.field = i.len.field, collapse = T)

g.part <- network(g.content.comp$edges, matrix.type = "edgelist", ignore.eval = FALSE, directed = TRUE)
b.graph.names = network.vertex.names(g.part)
set.seed(239)
p.refined <- ggnet2(g.part, label = F, edge.color = "black",
            # node.size = g.nodes.cnt[b.graph.names],
            node.size = 1,
            color = '#468B97',
            arrow.gap = 0.01, arrow.size = 2,
            # color = g.nodes.fam[b.graph.names],
            # palette = fam.palette,
            # mode = "kamadakawai"
            )

```

## Plot
```{r}
p.init
p.refined

```

# Stop
```{r}
stop('Script in progress...')
```


# Traits
```{r}
g.nodes.cnt = nodes.cnt$cnt
names(g.nodes.cnt) = nodes.cnt$node

b.graph.init = b.graph

g.part <- network(b.graph, matrix.type = "edgelist", ignore.eval = FALSE, directed = TRUE)
b.graph.names = network.vertex.names(g.part)

p <- ggnet2(g.part, label = F, edge.color = "black",
            node.size = g.nodes.cnt[b.graph.names],
            color = '#468B97'
            # color = g.nodes.fam[b.graph.names],
            # palette = fam.palette,
            # mode = "kamadakawai"
            )
p


```

# Output
```{r}

# nodes:
head(nodes)

# edges:
head(b.graph)

# Connected components
final.graph <- igraph::make_graph(t(b.graph), directed = T)
final.graph <- igraph::simplify(final.graph)
final.graph.comp <- igraph::components(final.graph)

# memnership
head(final.graph.comp$membership, 100)

```









