---
title: "Visualise synteny blocks between all accessions"
author: "Anna Igolkina"
output:
  html_document: 
    toc: true    
    toc_depth: 2 
    theme: "united" 
    highlight: tango 
---

# Setup

## Paths and libs
```{r}
library(ggplot2)
source('func_visualise_synteny.R')

path.data = '../01_data/'
path.figures = '../03_figures/'

path.proj = '../../../'
path.annot = paste(path.proj, '01_data_common/03_annot_repeat/', sep = '')
path.stat = paste(path.proj, '01_data_common/04_stat/', sep = '')
path.aln = paste(path.proj, '01_data_common/05_alignment/', sep = '')


n.acc = 28
n.chr = 5

file.idx.break = paste(path.data, 'blocks_all_v02.rds', sep = '')
file.cen.pos = paste(path.stat, 'cen_pos_fernando.txt', sep = '')
file.acc.len = paste(path.stat, 'chr_len.txt', sep = '')
```


## Paths on arriam
```{r}
path.aln = '/home/anna/storage/arabidopsis/pacbio/cmp_all/'

```


# Extract blocks from the alignment
(SERVER)
```{r}

idx.break = extractBlocks(path.aln, n.acc)
saveRDS(idx.break, file.idx.break, compress = F)

```


```{r}
idx.break = readRDS(file.idx.break)
colnames(idx.break)[c(3,4)] = c('own.b', 'own.e')

accessions = unique(idx.break$acc)
idx.break0 = idx.break

```


## Accession order per chromosome
```{r}

chr.order = list()
for(i.chr in 1:5){
  if (i.chr == 1){
    i.order = c(1,17,19,5,2,21,15,18,13,20,7,24,28,26,6,16,14,3,25,27,12,10,11,23,22,8,4,9)
  } else if(i.chr == 2){
    i.order = c(1,17,5,28,23,4,3,22,25,27,2,15,18,13,12,20,11,10,19,26,8,7,21,9,24,6,16,14)
  } else if (i.chr  == 3){
    i.order = c(1,17,5,2,21,20,7,24,26,6,3,27,12,10,8,4,9,22,23,11,25,16,14,28,15,18,13,19)
  } else if (i.chr == 4){
    i.order = c(1,17,5,2,21,15,18,13,20,7,24,28,16,14,3,25,8,9,6,23,19,26,27,12,10,11,22,4)
  } else if (i.chr == 5){
    i.order = c(1,17,23,19,5,2,21,15,18,13,20,7,24,28,26,6,16,14,3,25,27,12,10,11,22,8,4,9)
  }
  chr.order[[i.chr]] = i.order
}

```




# Save all chromosome figures
```{r}
wnd.size = 100000
for(i.chr in 1:n.chr){
  message(paste('Chromosome', i.chr))
  i.order = chr.order[[i.chr]]
  idx.break$acc <- factor(idx.break$acc, levels = accessions[i.order])

  p = ggSynteny(idx.break, i.chr, accessions, i.order, 
                file.cen.pos=file.cen.pos, file.acc.len=file.acc.len, wnd.size=wnd.size)
  
  pdf(paste(path.figures, 'fig_synteny_alignment_chr',i.chr,'.pdf', sep = ''), width = 7, height = 5)
  print(p)     # Plot 1 --> in the first page of PDF
  dev.off()
}
  
# p


```
# Visualise one chromosome
```{r}
i.order = chr.order[[i.chr]]
idx.break$acc <- factor(idx.break$acc, levels = accessions[i.order])

p = ggSynteny(idx.break, i.chr, accessions, i.order, 
              file.cen.pos=file.cen.pos, file.acc.len=file.acc.len, wnd.size = 100000)
p

p.init = ggSynteny(idx.break, i.chr, accessions, i.order, wnd.size = 100000)
p.init

```


