---
title: "Statistics about genes"
output: null_document
---

# Setup
```{r}

path.base = '../../../'

path.pannagram = paste(path.base, '../pannagram/', sep = '')

source(paste(path.pannagram, 'sim/sim_func.R', sep = ''))
source(paste(path.pannagram, 'sv/graph_refinement.R', sep = ''))
source(paste(path.pannagram, 'utils/utils.R', sep = ''))
source(paste(path.pannagram, 'visualisation/dotplot.R', sep = ''))
source(paste(path.pannagram, 'visualisation/msaplot.R', sep = ''))
source(paste(path.pannagram, 'visualisation/orfplot.R', sep = ''))
source(paste(path.pannagram, 'visualisation/visualisation.R', sep = ''))
```

## Libs
```{r}
invisible(library(ggplot2))
invisible(library(rhdf5))
```

## Paths
```{r}
path.annot = paste(path.base, '01_data/04_annotation/02_pannagram/genes_v05/', sep = '')
path.output = '../01_data/'

```


# Read
```{r}
files.annot = list.files(path.annot, pattern = "genes_v05_\\d+.gff$")
accessions = gsub("genes_v05_(\\d+).gff", "\\1", files.annot)

if(length(accessions) !=  length(files.annot)) stop('Problem with the format of gff files')

gff.all = c()
for(i.acc in 1:length(accessions)){
  pokaz('Accession', i.acc)
  gff = read.table(paste(path.annot, files.annot[i.acc], sep = ''), stringsAsFactors = F)
  gff = gff[gff$V3 %in% c('gene', 'mRNA'), ]
  
  # gff$V9 = sapply(gff$V9, function(s) substring(s, 1, 16 ))
  gff$V9 = sapply(gff$V9, function(s) strsplit(s, '\\.')[[1]][1])
  gff$V9 = sapply(gff$V9, function(s) strsplit(s, ';')[[1]][1])
  gff$V1 = sapply(gff$V1, function(s) strsplit(s, '_')[[1]][1])
  
  
  gff.all = rbind(gff.all, gff[, c(1,3,9)])
}
```

## Genes and mRNA
```{r}

as.data.frame.matrix

gff.tmp = gff.all[gff.all$V3 == 'gene',]
gene.table = as.data.frame.matrix(table(gff.tmp$V9, gff.tmp$V1))

gff.tmp = gff.all[gff.all$V3 == 'mRNA',]
mrna.table = as.data.frame.matrix(table(gff.tmp$V9, gff.tmp$V1))


if(length(setdiff(rownames(mrna.table), rownames(gene.table))) > 0) stop('Problem with gene names')
if(length(setdiff(colnames(mrna.table), colnames(gene.table))) > 0) stop('Problem with accession names 1')
if(length(setdiff(colnames(gene.table), colnames(mrna.table))) > 0) stop('Problem with accession names 2')
# Sorting of accessions
mrna.table = mrna.table[,colnames(gene.table)]


# Constructing mra table to fit the gene table
mrna.final = gene.table * 0
mrna.final[rownames(mrna.table),] = mrna.table

# mrna.final <- as.data.frame(mrna.final)
# gene.table <- as.data.frame(gene.table)

mrna.final$freq = rowSums(mrna.final)
gene.table$freq = rowSums(gene.table)

write.table(gene.table, 
            paste(path.output, 'genes_v05_freq_loci.txt', sep = ''), quote = F, sep = '\t', row.names = T, col.names = T)

write.table(mrna.final, 
            paste(path.output, 'genes_v05_freq_mrna.txt', sep = ''), quote = F, sep = '\t', row.names = T, col.names = T)



```

