---
title: "Tanglegram"
output: null_document
---

# Libs and variables
```{r}

# install.packages("ape")
# install.packages("dendextend")
# install.packages("ggtree")

library("ape")
library("dendextend")
library("ggtree")
library(ggplot2)  
library(cowplot)


path.data = '../01_data/'
path.figures = '../03_figures/'

f.tree1 = '1001g_v04_core.mafft-linsi.AA.IQtree_LG+I+R.bb1000.treefile'
f.tree2 = 'genes_v05_freq_loci.Anna.PA.IQtree_GTR2+I+R.bb1000.Bin.treefile'

```


## Colors
```{r}
addmix_colors_dict=c(admixed="#D88A32", africa ="#6069AC",asia ="#6FBAA4", central_europe="#ABCB67", 
                     china="#BB62A9",germany="#3E776C", italy_balkan_caucasus="#D2A63E",
                     madeira="#4A88BF", north_sweden="#70509A", relict="#DD6C60", south_sweden="#BC458B",
                     spain="#A6A99A",western_europe="#7E6363")

addmix=list(germany=c("1741","6909"),
            south_sweden=c("6024","6124"),
            north_sweden=c("6069","6244"),
            western_europe=c("6966","10002"),
            central_europe=c("8236","9728"),
            italy_balkan_caucasus=c("9075","9981"),
            spain=c("9537","9888"),
            relict=c("9543","9905"),
            asia=c("9638","10015"),
            admixed=c("9764"),
            africa=c("10024","22003","22004","22007"),
            china=c("22001","22002","220011"),
            madeira=c("22005","22006"))
```

# Functions
```{r}

rootOpt <- function(tree){
  
  n = length(tree$tip.label)
  mx = dist.nodes(tree)
  mx = mx[1:n, (n+1):ncol(mx)]
  d.max = apply(mx, 2, max)
  node.root = n + which(d.max == min(d.max))
  
  
  node.root
  get_descendants <- function(tree, node) {
    if (node > Ntip(tree)) {  # Проверяем, что это внутренний узел
      children <- list()
      descendants <- function(node) {
        if (!is.null(tree$edge)) {
          for (child in tree$edge[tree$edge[, 1] == node, 2]) {
            children <<- c(children, child)
            descendants(child)
          }
        }
      }
      descendants(node)
      return(children)
    } else {
      stop("Provided node is a tip, not an internal node.")
    }
  }
  
  children = unlist(get_descendants(tree, node.root))
  children = sort(children[children <= n])
  if(length(children) > n/2){
    children = setdiff(1:n, children)
  }
  
  tree_root = ape::root(tree, outgroup = children, resolve.root = TRUE)
  return(tree_root)
}

getTipOrder <- function(tree){
  n = length(t1$tip.label)
  x = tree$edge[,2]
  x = x[x <= n]
  return(tree$tip.label[x])
}

reorderTree <- function(t1, t2){
  

  n = length(t1$tip.label)
  
  tip2 = getTipOrder(t2)
  tip1 = getTipOrder(t1)
  
  indices_vec_ini <- match(tip1, tip2)
  a_ini = abs((1:n) - indices_vec_ini)
  d_ini = sum(a_ini)
  
  
  for(i.node in (n+1):(2*n - 1)){
    # print(i.node)
    if(!(i.node %in% t1$edge[,1])) next
    # stop()
    t1_rot = ape::rotate(t1, node=i.node)
    # plot(t1_rot)
    
    tip1_rot =  getTipOrder(t1_rot)
    
    indices_vec_rot <- match(tip1_rot, tip2)
    a_rot = abs((1:n) - indices_vec_rot)
    d_rot = sum(a_rot)
    
    if(d_rot < d_ini){
      d_ini = d_rot
      a_ini = a_rot
      t1 = t1_rot
    } else if(d_rot == d_ini){
      tmp = which(a_rot != a_ini)
      b.rot = a_rot[tmp]
      b.ini = a_ini[tmp]
      if(var(b.rot) < var(b.ini)){
        # stop()
        d_ini = d_rot
        a_ini = a_rot
        t1 = t1_rot
      }
    }
    
  }
  return(t1)
}

```




# Read trees
```{r}

t1 <- read.tree(paste(path.data, f.tree1, sep = ''))
t2 <- read.tree(paste(path.data, f.tree2, sep = ''))


```



## Root
```{r}

t1 = rootOpt(t1)
t2 = rootOpt(t2)

is.rooted(t1)
is.rooted(t2)

# plot(t1)

```

## Reorder
```{r}

t1 = reorderTree(t1, t2)
t2 = reorderTree(t2, t1)


```

# Plot tanglegram
```{r}

y.expand = 0.02


T1 <- ggtree(t1, ladderize=F) +    
  theme_tree2(legend.position='none', plot.margin = unit(c(0,0,0,0),"cm")) +
  geom_tiplab(align = TRUE) +
  ggtree::geom_text2(aes(label=label, 
                          subset = !is.na(as.numeric(label)) & as.numeric(label) >=75 & as.numeric(label) <=100),
                     size = 2,
                     hjust = 1, 
               vjust = -1.5, color = 'grey30') +
  scale_y_continuous(expand = c(y.expand, y.expand))


T1=ggtree::groupOTU(T1, addmix) + 
  aes(color=group) + scale_color_manual(values=addmix_colors_dict)



T2 <- ggtree(t2, ladderize=F) +   
  theme_tree2(legend.position='none', plot.margin = unit(c(0,0,0,0),"cm")) +
  geom_tiplab(hjust =1, align = TRUE) +
ggtree::geom_text2(aes(label=label, 
                          subset = !is.na(as.numeric(label)) & as.numeric(label) >=75 & as.numeric(label) <=100),
                     size = 2,
                     hjust = 1, 
               vjust = -1.5, color = 'grey30') +
  scale_y_continuous(expand = c(y.expand, y.expand))



T2=ggtree::groupOTU(T2, addmix) + 
  aes(color=group) + scale_color_manual(values=addmix_colors_dict)


d1 = T1$data[T1$data$isTip,]  
d1$x[] = 1  
d2 = T2$data[T2$data$isTip,]  
d2$x[] = 2  

TTcon <- rbind(d1, d2)  


L1 = ggplot(TTcon, aes(x = x, y = y, colour = group, group = label)) + geom_line() +
  theme_void() + theme(legend.position="none", plot.margin = unit(c(1,0,1,0),"cm")) +
  scale_y_continuous(expand = c(y.expand, y.expand)) + 
  scale_color_manual(values=addmix_colors_dict)   #+ theme(legend.position = "bottom")  
L1


# + guides(color = guide_legend(nrow = 4)) +theme(legend.position = "bottom")

cowplot::plot_grid(T1 + xlim(c(0, 0.010)) + ggtitle('AA variation') , 
                   L1 ,
                   T2 + scale_x_reverse(limits = c(0.06, 0)) + ggtitle('Gene presence variation'), 
                   nrow = 1, align = "hv")


```



